### ISSUE TITLE
npx hardhat gobind failed with error (total length of command line and environment variables exceeds limit)

### ISSUE THREAD

**Issue by daniel-fi** [dl-solarity/hardhat-gobind#12]
> npx hardhat gobind

An unexpected error occurred:

Error in plugin @dlsl/hardhat-gobind: total length of command line and environment variables exceeds limit

Need to merge process.env?

https://github.com/dl-solarity/hardhat-gobind/blob/b28f5c72cbdcc216030b4b5811cf1d9a2e781720/src/abigen/generator.js#L111

**Comment by nikicat** [comment]
Your environment is too long (see https://github.com/golang/go/issues/31105). Try to clean some of your env before executing `npx hardhat gobind`
